add_newline = false

[directory]
read_only = " "
style = "bold #61afef"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #c678dd"

[git_status]
ahead = "${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
staged = "${count}"
deleted = "${count}"
untracked = "${count}"
modified = "${count}"
style = "bold #e06c75"
