add_newline = false

[directory]
read_only = " "
style = "bold blue"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold blue"

[git_status]
ahead = "${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
staged = "${count}"
deleted = "${count}"
untracked = "${count}"
modified = "${count}"
style = "bold red"

[hostname]
format = "[$hostname](bold blue) in "

[username]
format = "[$user](bold blue) on "
